### ISSUE TITLE
ICAO Implementation differs from vaccination implementation

### ISSUE THREAD

**Issue by jona7o** [corona-warn-app/cwa-quicktest-onboarding#68] opened 2021-12-08 21:39 UTC
Hi,

we are a software development company with a product for COVID19 test- and vaccination centers. For this use case we create both, vaccination certificates over ubirch/ibm api and test certificates over the cwa endpoint. Today I found a miss match between these two certificates for the same input.

I think this bug is located in the ubirch/ibm api because i think the dot char "." is not specified for a machine readable string and gets replaced by nothing and not with an "<" char. If it is defined this is a bug in the reference implementation of the cwa. I'll open these requests in both github repositorys and link each other. Could someone clarify which implementation is correct?

**Example for Vaccination certificates with Ubirch/IBM API:**
"fn": "Dr. Mustermann",
"gn": "Max",
"fnt": "DR<<MUSTERMANN",
"gnt": "MAX"
 
**Example for Test over CWA API**
"fn": "Dr. Mustermann",
"gn": "Max",
"fnt": "DR<MUSTERMANN",  
"gnt": "MAX" 

Regards, Tobias

https://github.com/Digitaler-Impfnachweis/certification-apis/issues/209

**Comment by ilya-smirnov-berlin** [comment] 2021-12-29 09:26
Not a bug in CWA. Should be fixed for certifications APIs.

**Closed by ilya-smirnov-berlin** 2021-12-29 09:26 UTC
Labels: bug
