### ISSUE TITLE
Personalized positive test result

### ISSUE THREAD

**Issue by thimobuchheister** [corona-warn-app/cwa-quicktest-onboarding#32] opened 2021-07-25 15:56 UTC
## Test result in CWA without personal information for positive test results

If we submit an issue with personal data included, the negative test result shows up with the personal information in the CWA. For positive test results, we only get the result without any personal information in the app. **Is this the intended behavior?**

I cannot find any information on this, but I also cannot find any image for a personalized positive test result.

**Comment by Ein-Tim** [comment] 2021-07-25 16:00
I'm quite certain that this is intended. There is also no code in the apps which would allow to show the positive test result with personal data. There is no need for this in the CWA.

**Comment by maryisdead** [comment] 2021-07-27 11:17
This is intended. Confirmed when we had our integration approved.

**Comment by Ein-Tim** [comment] 2021-07-27 11:40
Thanks for the confirmation @maryisdead!

If you consider this as solved @thimobuchheister, please close this issue.

**Comment by ilya-smirnov-berlin** [comment] 2021-07-29 08:11
The question was answered.

**Closed by ilya-smirnov-berlin** 2021-07-29 08:11 UTC
Labels: question
